#!/usr/bin/env python3
"""Write the gresource manifest that carries the bundled themes inside the exe.

	gen-theme-resources.py <repo-root> [out-xml]

The bundled themes used to ship as loose files beside the exe - about 2,200 of
them once the icon sets are counted. The Windows single-exe packer charges for
every file it carries at every launch (measured at ~2.8 ms each), so they ride
inside the binary as one resource blob instead.

Two things follow from how GTK reads icons out of resources:

  - A resource path is searched as though it were part of hicolor, so the
	directory names have to be ones hicolor defines. Our symbolic/ folders are
	not, and are folded into scalable/ - the -symbolic suffix on the filename is
	what marks a glyph monochrome, not the folder it sits in.
  - index.theme is never read from a resource path. Ours carry the style, the
	modes and the light/dark counterpart that the picker needs, so they are
	copied into a catalog prefix the app reads itself.

Re-run after changing anything under vendor/icons, vendor/themes or
assets/icons. vendor-themes.bash does it for you.
"""

##	Copyright © 2026 Bubbles (ID: XଌฅრX۳ᛟԃლፀƅꓩหδლც)
##	Licensed under The MIT License (MIT). Full text at:
##		https://mit-license.org/
##	SPDX-License-Identifier: MIT

import os
import sys
from xml.sax.saxutils import escape

# Where each kind of theme is drawn from, repo-relative.
ICON_DIRS = ("vendor/icons", "assets/icons")
WIDGET_DIRS = ("vendor/themes",)

# Built by a tool, meaningless inside a resource, or not ours to ship.
SKIP_NAMES = {"icon-theme.cache", ".gitignore", "thumbnail.png"}

# Text compresses to a fraction of itself; png and the like already are.
COMPRESS_SUFFIXES = (".svg", ".css", ".theme", ".xml", ".txt")


def theme_dirs(root, subdirs):
	"""Every immediate subdirectory of @subdirs, as (name, abs path), sorted."""
	found = []
	for sub in subdirs:
		base = os.path.join(root, sub)
		if not os.path.isdir(base):
			continue
		for name in sorted(os.listdir(base)):
			path = os.path.join(base, name)
			if os.path.isdir(path):
				found.append((name, path))
	return found


def walk_files(theme_dir):
	"""Files under @theme_dir as paths relative to it, sorted, skips excluded."""
	out = []
	for base, _dirs, files in os.walk(theme_dir):
		for name in sorted(files):
			if name in SKIP_NAMES:
				continue
			rel = os.path.relpath(os.path.join(base, name), theme_dir)
			out.append(rel.replace(os.sep, "/"))
	return sorted(out)


def icon_alias(rel):
	"""Where an icon file goes inside the theme's resource path.

	GTK matches a resource path against hicolor's directory list, which has no
	symbolic/ in it, so those files move to scalable/ under the same context.
	"""
	if rel.startswith("symbolic/"):
		return "scalable/" + rel[len("symbolic/"):]
	return rel


def emit(handle, alias, source):
	compressed = alias.endswith(COMPRESS_SUFFIXES)
	handle.write('\t\t<file alias="%s"%s>%s</file>\n' % (
		escape(alias),
		' compressed="true"' if compressed else "",
		escape(source)))


def main(argv):
	if len(argv) < 2:
		sys.stderr.write(__doc__)
		return 2

	root = os.path.abspath(argv[1])
	out = argv[2] if len(argv) > 2 else os.path.join(
		root, "source", "gresources", "nemo-themes.gresource.xml")

	icons = theme_dirs(root, ICON_DIRS)
	widgets = theme_dirs(root, WIDGET_DIRS)
	files = 0
	clashes = []

	os.makedirs(os.path.dirname(out), exist_ok=True)
	with open(out, "w", encoding="utf-8", newline="\n") as handle:
		handle.write('<?xml version="1.0" encoding="UTF-8"?>\n')
		handle.write("<!-- Generated by cicd/utility/gen-theme-resources.py - do not hand-edit. -->\n")
		handle.write("<gresources>\n")
		handle.write('\t<gresource prefix="/org/nemo/themes">\n')

		for name, path in icons:
			seen = {}
			for rel in walk_files(path):
				source = os.path.relpath(os.path.join(path, rel), root).replace(os.sep, "/")
				if rel == "index.theme":
					emit(handle, "catalog/icons/%s/index.theme" % name, source)
					files += 1
					continue
				alias = "icontheme/%s/%s" % (name, icon_alias(rel))
				if alias in seen:
					clashes.append("%s: %s and %s both land on %s" % (
						name, seen[alias], rel, alias))
					continue
				seen[alias] = rel
				emit(handle, alias, source)
				files += 1

		for name, path in widgets:
			for rel in walk_files(path):
				source = os.path.relpath(os.path.join(path, rel), root).replace(os.sep, "/")
				if rel == "index.theme":
					emit(handle, "catalog/themes/%s/index.theme" % name, source)
					files += 1
					continue
				emit(handle, "widgettheme/%s/%s" % (name, rel), source)
				files += 1

		handle.write("\t</gresource>\n")
		handle.write("</gresources>\n")

	for clash in clashes:
		sys.stderr.write("WARNING %s\n" % clash)

	print("%d icon themes, %d widget themes, %d files -> %s" % (
		len(icons), len(widgets), files, out))
	return 1 if clashes else 0


if __name__ == "__main__":
	sys.exit(main(sys.argv))
